name: "ZeroTier"
description: "Connect your Github Action workflow to ZeroTier"
branding:
  icon: 'globe'
  color: 'gray-dark'

on:
  workflow_call:

inputs:
  network_id:
    description: "The ZeroTier network ID to connect to"
    required: true
  auth_token:
    description: "Your ZeroTier Central API Access Token"
    required: true
  api_url:
    description: "ZeroTier Central API URL"
    required: false
    default: "https://my.zerotier.com/api/v1"

runs:
  using: 'composite'
  steps:
    - name: zerotier
      uses: ./util/post
      with:
        main: ./main.sh
        post: ./post.sh
